{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7e8a136c-94f1-4e33-8c3c-21fe5d48177f",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app 'app.my_app' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: on\n",
      " * Running on all addresses.\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      " * Running on http://192.168.101.7:8000/ (Press CTRL+C to quit)\n",
      " * Restarting with stat\n",
      " * Debugger is active!\n",
      " * Debugger PIN: 104-253-136\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[36mGET /templates/Image/sample_target/04697.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:17] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[36mGET /templates/Image/sample_target/sketch_330_000054.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:21] \"\u001b[36mGET /templates/colors/blue.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"GET /templates/Image/sample_target/00269.jpg HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"\u001b[36mGET /templates/colors/blue.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:25] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[36mGET /templates/Image/sample_target/00533.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:29] \"\u001b[36mGET /templates/colors/bluepurple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[36mGET /templates/colors/blue.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[36mGET /templates/Image/sample_target/04373.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:33] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193436792576 and this is thread id 140193428399872.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405b70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193436792576 and this is thread id 140193428399872.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193436792576 and this is thread id 140193428399872.\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[36mGET /templates/Image/sample_target/02705.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[36mGET /templates/colors/bluepurple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:37] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:40] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:40] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:40] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:40] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:41] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:41] \"\u001b[36mGET /templates/Image/sample_target/sketch_257_000125.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:41] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"GET /templates/Image/sample_target/05870.jpg HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:45] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405b70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[36mGET /templates/Image/sample_target/00897.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:49] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:54] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:54] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:54] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:54] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:55] \"\u001b[36mGET /templates/Image/sample_target/04782.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:55] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:36:55] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"\u001b[36mGET /templates/Image/sample_target/00269.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:04] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405b70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[36mGET /templates/Image/sample_target/08323.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:08] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[36mGET /templates/Image/sample_target/03025.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:39] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[36mGET /templates/Image/sample_target/sketch_010_000102.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:43] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193428399872.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405b70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193428399872.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193428399872.\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[36mGET /templates/Image/sample_target/01921.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:46] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:50] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"\u001b[36mGET /templates/Image/sample_target/05453.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:51] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[36mGET /templates/Image/sample_target/00897.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:37:57] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405e40>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193419482880.\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:01] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:01] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:02] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:02] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:02] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:02] \"\u001b[36mGET /templates/Image/sample_target/00897.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:02] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[36mGET /templates/Image/sample_target/04697.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:06] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[36mGET /templates/Image/sample_target/03700.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:10] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[36mGET /templates/Image/sample_target/06217.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:16] \"\u001b[36mGET /templates/colors/bluepurple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:21] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:21] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:21] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:21] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:22] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:22] \"\u001b[36mGET /templates/Image/sample_target/08323.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:22] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[36mGET /templates/Image/sample_target/05479.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:26] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8152754210>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[36mGET /templates/Image/sample_target/sketch_186_000129.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:31] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[36mGET /templates/Image/sample_target/sketch_121_000228.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:35] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[36mGET /templates/Image/sample_target/03025.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:39] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:43] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:43] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:44] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:44] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:44] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:44] \"\u001b[36mGET /templates/Image/sample_target/00407.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:44] \"\u001b[36mGET /templates/colors/green.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405c60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405d50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405990>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405b70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193428399872 and this is thread id 140193436792576.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405e40>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f81527543f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[36mGET /templates/Image/sample_target/sketch_165_000210.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:47] \"\u001b[36mGET /templates/colors/bluepurple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"GET /templates/Image/sample_target/01310.jpg HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:51] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7f8159405e40>\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 682, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 887, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 667, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 244, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/opt/conda/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 673, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140193419482880 and this is thread id 140193436792576.\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[36mGET /templates/colors/yellow.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[36mGET /templates/Image/sample_target/05870.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:55] \"\u001b[36mGET /templates/colors/white.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[36mGET /templates/colors/yellowred.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[36mGET /templates/Image/sample_target/06368.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:38:59] \"\u001b[36mGET /templates/colors/bluepurple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[36mGET /templates/colors/purple.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[36mGET /templates/Image/sample_target/06778.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:02] \"\u001b[36mGET /templates/colors/blue.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[32mPOST /add HTTP/1.1\u001b[0m\" 302 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"GET /task/hypara_test HTTP/1.1\" 200 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[36mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[36mGET /static/js/bootstrap.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[36mGET /templates/colors/red.png HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[36mGET /templates/Image/sample_target/03025.jpg HTTP/1.1\u001b[0m\" 304 -\n",
      "192.168.100.18 - - [02/Sep/2021 15:39:06] \"\u001b[36mGET /templates/colors/black.png HTTP/1.1\u001b[0m\" 304 -\n"
     ]
    }
   ],
   "source": [
    "!python run.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8f35ade-d11f-4895-a78f-3e80ef5b1dc4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
